### ISSUE TITLE
Make the distributor output the criticaltime/time to breach SLA counters

### ISSUE THREAD

**Issue by SimonCropp** [Particular/NServiceBus.Distributor.Msmq#17]
Raised by @andreasohlund
Migrated from by https://github.com/Particular/NServiceBus/issues/1279

Have each worker send back the critical time calculated as header in the control message going back to the distributor so that the distributor can populate it's counter. This allows for centralized monitoring of SLA's by just looking at the distributor

**Comment by johnsimons** [comment]
@andreasohlund @dannycohen is this still in the roadmap?

**Comment by andreasohlund** [comment]
Given the new routing I'd say no, let's close. @dannycohen ?

**Comment by dannycohen** [comment]
by all means.
