### ISSUE TITLE
Remove the support for running workers and distributor on the same box

### ISSUE THREAD

**Issue by SimonCropp** [Particular/NServiceBus.Distributor.Msmq#18]
Raised by @andreasohlund
Migrated from by https://github.com/Particular/NServiceBus/issues/2048

The code we have to generate unique input queues for workers running locally for demo purposes I constantly confusing users.  It's time to kill it.

Full context:
https://groups.google.com/forum/m/?utm_medium=email&utm_source=footer#!msg/particularsoftware/mBeAWMQ5JOE/KsE5gS4DL8UJ

**Comment by johnsimons** [comment]
This is already done as part of https://github.com/Particular/NServiceBus.Distributor.Msmq/commit/517beaaeb4d0607d9f39aa9fd41fed3d54294508#diff-b39dc4c9d92df96f8f8ddde081f7abacR35
