### ISSUE TITLE
Do not check persistence queue during construction of MsmqWorkerAvailabilityManager 

### ISSUE THREAD

**Issue by SzymonPobiega** [Particular/NServiceBus.Distributor.Msmq#25]
### Symptoms

Installation of NServiceBus fails with exception thrown by ```MsmqWorkerAvailabilityManager``` saying it can't access the queue.

### Who's affected

All users of external distributor (NServiceBus.Distributor.MSMQ) who want to use a non-default container (other than Autofac)

### Root cause

Other containers have different ordering of components for multiple registration than Autofac. It changes the order of installers making satellite queue creator run before distributor persistence queue creator. The former tries to instantiate a distributor satellite which in turn tries to instantiate the availability manager causing the exception.

### Possible solutions

 * Check the persistence queue when first accessed (via property getter)
 * Bring back the ```Start()``` method removed from ```IWorkerAvailabilityManager```

**Comment by SzymonPobiega** [comment]
@johnsimons what do you think we should do? @andreasohlund voted for bringing back the ```Start()``` method

**Comment by johnsimons** [comment]
I guess the question is why is `MsmqWorkerAvailabilityManager` being newed up at install time ?

**Comment by SzymonPobiega** [comment]
Because it is a part of satellite. And you need to instantiate a satellite to get its input address. The bigger question is why using a single class to model such a complex being as satellite. Getting the input address has nothing to do with processing messages and yet both are defined as instance method on ISatellite.

**Comment by johnsimons** [comment]
Yeah I saw that, anyway I hacked it and it seems to work

**Comment by johnsimons** [comment]
Fixed in https://github.com/Particular/NServiceBus.Distributor.Msmq/commit/2ac365343e5504fa2191e0b322191b66fe3c462d
