### ISSUE TITLE
Distributor tries to reuse expired worker entires in the storage queue over and over

### ISSUE THREAD

**Issue by janovesk** [Particular/NServiceBus.Distributor.Msmq#28]
### Symptoms

Endless log entries of type ```Logs Session ids for Worker at '{0}' do not match, so poping next available worker``` until distributor for endpoint is restarted.

Orginally [reported](https://groups.google.com/forum/#!topic/particularsoftware/omUFBDlkX3I) on the google group.
### Who's affected

Some users of external distributor (NServiceBus.Distributor.MSMQ). Unclear what triggers the situation for now.

### Root cause

Distributor tries to pop a worker, but the worker has session id not equal to the active session id stored by the distributor for that worker address. A info entry is written to the log with ```Session ids for Worker at '{0}' do not match, so poping next available worker```. Tries next worker. Same thing happens for all workers in the storage queue. No worker with the active session id is found. The end result is the transaction, including both the message and the expired workers popped from the storage queue, rolling back. The entire thing repeats forever unless distributor is restarted, which cleares the active session id-cache.

The big question is how one got into the situation with ONLY worker with expired sessions is in the distributor storage queue in the first place. 

### Possible solutions

 * Remove workers with expired session ids from the storage queue when detected. This needs to happen OUTSIDE the surrounding transaction.

**Comment by janovesk** [comment]
One possible explaination for this would be a rollback of the handler for a worker startup message on the distributor AFTER the internal active sessions id-cache has been updated.

**Comment by janovesk** [comment]
Or a race condition between a new worker startup message and an old ready message.

**Comment by janovesk** [comment]
Pretty sure the problem is the following scenario. 

RWA = Registered Worker Address. This is an in memory cache on the distributor storing the latest sessionId for every worker.  
SQ: Storage Queue on the distributor

1. Worker A starts, sessionId A1. Sends start message with A1 to Distributor.
2. Distributor RWA:A1 SQ:A1
3. Distributor sends A1 to Worker A
4. Distributor RWA:A1 SQ:
5. Worker A restart, session id A2. Sends start message with A2 to Distributor.
6. Distributor RWA:A2 SQ:A2
7. Distributor restart 
8. Distributor RWA:   SQ:A2
9. Distributor receives delayed ready message with A1
10 .Distributor RWA:A1 SQ:A2,A1
11. Distributor sends A1 to Worker A  - no ready message sent back to distributor because Worker A has session id A2
12. Distributor RWA:A1 SQ:A2   - infinte failure because no match between RWA and SQ is possible.

**Comment by janovesk** [comment]
Working on getting a reliable repro.

**Comment by janovesk** [comment]
It's actually even worse. All you need is a worker restarting before restarting its distributor.

RWA = Registered Worker Address. This is an in memory cache on the distributor storing the latest sessionId for every worker.

SQ: Storage Queue on the distributor

1. Worker A starts, sessionId A1. Sends start message with A1 to Distributor.
2. Distributor RWA:A1 SQ:A1
3. Worker A restart, session id A2. Sends start message with A2 to Distributor.
4. Distributor RWA:A2 SQ:A1,A2
5. Distributor restart 
6. Distributor RWA:   SQ:A1,A2
7. Distributor receives incoming message. Pops first in SQ = A1. Sets RWA=A1
8. Distributor sends A1 to Worker A   - no ready message sent back to distributor because Worker A has session id A2
9. Distributor RWA:A1 SQ:A2 - very bad. Will never find available worker.
10. Distributor receives incoming message. - Fail forever with "do not mach, so popping next available worker" error.

**Comment by janovesk** [comment]
Have a working repro now, figuring out how to fix it. :)

**Comment by indualagarsamy** [comment]
@janovesk - link to repro?

**Comment by janovesk** [comment]
Please chime in on the [requirements issue](https://github.com/Particular/Requirements/issues/248), @indualagarsamy and @johnsimons.

**Comment by indualagarsamy** [comment]
Fixed in 5.0.3
