### ISSUE TITLE
DoNotWrapHandlersExecutionInATransactionScope leads to extra ready messages

### ISSUE THREAD

**Issue by janovesk** [Particular/NServiceBus.Distributor.Msmq#30]
Versions: 4.0.2 & 4.7.5

We've been having some problems with a distributor working correctly in our production environment. We noticed that when work was completed on a worker, that it would send 2 worker ready messages back to the distributor which would then have the side effect of work getting queued up on workers while other workers were performing no processing as the worker ready messages in the distributor storage queue was inaccurate.

It took awhile to debug and determine where the problem was, I initially upgraded to 4.7.5 as we're currently on 4.0.2 to see if it resolved the issue with the new NServicebus.Distributor.MSMQ package and session id's which it did not.

We then noticed that on the endpoint at hand, we had disabled transaction wrapping as we needed information out of the endpoint before it was done processing. We were disabling the transaction scope with:

Configure.Transactions.Enable().Advanced( x => x.DoNotWrapHandlersExecutionInATransactionScope() );

The issue was resolved by removing this config and restructuring the worker to send the information we needed before the message was sent to the distributor. I'm opening a thread here just to bring the issue to light and see if you are aware, or if there is even a way to resolve this, or perhaps this may help someone in the future.

It seems like the worker ready mechanism sends a "worker ready" message anytime a "message" is sent from an endpoint. I'm assuming that the definition of a message being sent is from the transaction scope so that one completed send of all messages (we were sending 2 messages from the worker from the handler), it would only send one worker ready message. In our case, it seems like once the transaction wrapping is disabled, every message sent is considered a worker ready message as I'm assuming NSB has no way to discern if the message being sent is from the same handler processing.

Hopefully this helps someone in the future, it took us a little while to determine what was going on and in the end, ended up being obvious.

Thanks!

Sean Chambers

Orignally from: https://groups.google.com/forum/#!topic/particularsoftware/BMu5TBAE5YA

**Comment by janovesk** [comment]
I'm able to replicate something similar to this if a handler throws an exception.

**Comment by andreasohlund** [comment]
In v6 we should fix this by making the ready message sender a behavior and configure it to inject before the SuppressAmbientTransactionBehavior added in v6

**Comment by andreasohlund** [comment]
This seems to cause a ready message build up eventually causing the storage queue running out of quota?

**Comment by schambers** [comment]
We are still noticing this behavior today. Any updates or workarounds available in 4.x for this? I know its an older version but we have quite a bit of infrastructure to do a major upgrade

**Comment by SzymonPobiega** [comment]
@schambers can you post your handler code? The ready messages are sent each time a worker receives a message from the distributor (https://github.com/Particular/NServiceBus.Distributor.Msmq/blob/develop/src/NServiceBus.Distributor.MSMQ/ReadyMessages/ReadyMessageSender.cs#L44) so probably suppressing the transaction scope has some influence on this behavior. 

On of the reasons might be that your ready messages are being sent to the distributor even if the incoming message failed processing and is returned to worker's input queue but I suspect there is also other issue that causes this duplicate sending behavior your are observing.

**Comment by schambers** [comment]
Sorry this was not followed up on. More input:

We are also sending a "HandleException" message if processing fails as part of a custom fault manager so I think I would need to include not only the handler code, but also what our fault manager is doing as part of managing message failures.

Do you have an e-mail where I can send the relevant code to. I'm currently in the process of upgrading 4.0.2 to 5.2.19 and I'm going through testing now to see if it's still an issue which I suspect it is.

**Comment by SzymonPobiega** [comment]
@schambers you can post the code to my e-mail address `szymon.pobiega` at `particular.net`. The *ready* messages should be fine if you use the default transaction settings (wrapping everything in a distributed transaction) but I'd like to take a look at that custom fault manager to ensure it works as you expect.
