### ISSUE TITLE
When MasterNodeConfig section is not present the validation output could be improved

### ISSUE THREAD

**Issue by ramonsmits** [Particular/NServiceBus.Distributor.Msmq#33]
When MasterNodeConfig section is not present the following error is shown:

> 2015-12-15 11:52:35.033 ERROR NServiceBus.GenericHost Exception when starting endpoint. System.Configuration.ConfigurationErrorsException: 'MasterNodeConfig.Node' entry should point to a valid host name. Currently it is: [].

The MasterNodeConfig section is not present at all.

To reproduce use the scaleout sample and comment MasterNodeConfig of a worker and comment the `NServiceBus/Distributor/WorkerNameToUseWhileTesting` app setting.

**Comment by andreasohlund** [comment]
Since we're sun setting the distributor we're not adding more improvements
