### ISSUE TITLE
Distributor stops dispatching work after restart if workers are busy

### ISSUE THREAD

**Issue by ramonsmits** [Particular/NServiceBus.Distributor.Msmq#34]
The distributor stops dispatching message to workers after it restarts (same machine or another cluster node) if all workers are consuming message at the moment the distributor stops / quits / crashes.

Ready messages send to the distributor after a restart are ignored.

## How to reproduce:

Take the following steps to reproduce this issue:

- Take the distributor scaleout sample
- Add a thread sleep to the worker handler of 10 seconds
- Send 4 messages
 - 2 will be dispatched to the workers, 2 remain in the distributor queue
- Stop the distributor
- Wait until the workers complete
- Start the distributor
- Distributor now dis

Now the backlog will not be processed and message pile up.

## Workaround

You have to restart the worker so that in re-enlist itself at the distributor but this obviously is not suffecient for when the distributor restarts or rolls over to a different node in a cluster.

## Solution

The solution is to not ignore the ready messages send by the worker.

A minor issue is that when the worker is restarted it could temporarily have more messages in its queue then the configured concurrency limit is set. This is due the ready message send at start which instructs the distributor to enlist the worker for work.

## Affected supported versions

Based on our release policy the following NServiceBus.Distributor.MSMQ versions need patching:

- 5.0.x => [5.0.4](https://github.com/Particular/NServiceBus.Distributor.Msmq/milestones/5.0.4), pull request #35
- 4.4.x => [4.4.9](https://github.com/Particular/NServiceBus.Distributor.Msmq/milestones/4.4.9), pull request #39

**Comment by ramonsmits** [comment]
@janovesk Might V4 also be affected? What do we do if it is? Its no data loss so no backport to previous versions I think. //cc @andreasohlund ?

**Comment by janovesk** [comment]
http://docs.particular.net/nservicebus/upgrades/release-policy say we support version 4 until 2016-07-11, so we should backport this to 4.8.

**Comment by ramonsmits** [comment]
@janovesk The PR is already linked to the milestone.

**Comment by ramonsmits** [comment]
@janovesk I added the affected versions to the description and the solution.

**Comment by ramonsmits** [comment]
Bug is fixed in 5.0.4 and 4.4.9 but is not yet published.

**Comment by mauroservienti** [comment]
@Particular/platform-dev-squad this is missing a proper task force, @ramonsmits @janovesk please ping people to set up one.
