### ISSUE TITLE
When worker is stopped it should signal the distributor and drain its queue

### ISSUE THREAD

**Issue by ramonsmits** [Particular/NServiceBus.Distributor.Msmq#38]
When a worker is stopped it should signal the distributor and drain its queue.

Changes
- A windows service stop should 'wait' until worker threads are idle
- During a stop it should not send a ready message to the distributor when shutting down
- Send a message to the distributor that prevents messages to be forwarded to the worker

**Comment by andreasohlund** [comment]
Since we're sun setting the distributor we won't add new features. Closing this
